---
# https://backstage.io/docs/features/software-catalog/descriptor-format#kind-system
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: Personalization.Vesta
  description: |
    Manages (update / delete) customer information (Name, Gender, Language etc.) which is used for personalization / recommandations.
    Also the service coordinates the requested GDPR / DSGVO delete of users to all other services from team Darwin.
    And it also handles Coupon Subscriptions for customers (i.e. if a customer wants to receive coupons (Persönliche Kundenvorteile) via email or not).
  labels:
    dg.darwin.semantic-name: Shared.UserIdentityData
    dg.darwin.context: shared
    example.com/custom: custom_label_value
    galaxus.ch/darwin-semantic-name: Shared.UserIdentityData
  tags:
   - csharp
   - gcp
spec:
  owner: darwin
---
# https://backstage.io/docs/features/software-catalog/descriptor-format#kind-component
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: Vesta.Api
  description: REST API to get Customer information and Coupon Subscriptions.
  annotations:
    dev.azure.com/project-repo: devinite/Personalization.Vesta
    backstage.io/kubernetes-id: vesta
    backstage.io/kubernetes-namespace: default
    backstage.io/kubernetes-label-selector: "app=vesta"
  links:
    - title: GCP logs
      icon: dashboard
      type: gcplogs
      url: https://console.cloud.google.com/logs/query;query=labels.k8s-pod%2Fapp%3D%22vesta%22?project=dg-pers-prod
spec:
  type: service
  lifecycle: production
  owner: darwin
  system: Personalization.Vesta
---
# https://backstage.io/docs/features/software-catalog/descriptor-format#kind-component
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: Vesta.DSGVO
  description: Uses Google PUB/SUB for listening to messages to permanently delete customer information from BigQuery.
  annotations:
    dev.azure.com/project-repo: devinite/Personalization.Vesta
    backstage.io/kubernetes-id: vesta-dsgvo
    backstage.io/kubernetes-namespace: default
  links:
    - title: GCP logs
      icon: dashboard
      type: gcplogs
      url: https://console.cloud.google.com/logs/query;query=labels.k8s-pod%2Fapp%3D%22vesta-dsgvo%22?project=dg-pers-prod
spec:
  type: service
  lifecycle: production
  owner: darwin
  system: Personalization.Vesta
---
# https://backstage.io/docs/features/software-catalog/descriptor-format#kind-component
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: Vesta.Hephaestus
  description: |
    Uses Google PUB/SUB for three main things.
    It subscribes / unsubscribes customers to coupons.
    It also coordinates GDPR / DSGVO deletion requests of customers to all other services (including itself) and accepts & records confirmations of deletions from the other services.
    And thirdly it also upserts and (soft) deletes customer data.
  annotations:
    dev.azure.com/project-repo: devinite/Personalization.Vesta
    backstage.io/kubernetes-id: vesta-hephaestus
    backstage.io/kubernetes-namespace: default
  links:
    - title: GCP logs
      icon: dashboard
      type: gcplogs
      url: https://console.cloud.google.com/logs/query;query=labels.k8s-pod%2Fapp%3D%22vesta-hephaestus%22?project=dg-pers-prod
spec:
  type: service
  lifecycle: production
  owner: darwin
  system: Personalization.Vesta
---

